-- MySQL Script generated by MySQL Workbench
-- Mon 14 Aug 2017 07:31:53 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_content_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_content_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_content_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_content_service` ;

-- -----------------------------------------------------
-- Table `ulbora_content_service`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_content_service`.`content` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `category` VARCHAR(75) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `modified_date` DATETIME NULL,
  `hits` BIGINT NOT NULL DEFAULT 0,
  `meta_author_name` VARCHAR(100) NULL,
  `meta_desc` VARCHAR(500) NULL,
  `meta_key_words` VARCHAR(250) NULL,
  `meta_robot_key_words` VARCHAR(250) NULL,
  `text` LONGBLOB NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
